import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import morgan from 'morgan';
import { env } from './config/env.js';
import { requireAuth } from './middleware/auth.js';
import { requireIntegrationAuth } from './middleware/integrationAuth.js';
import { errorHandler, notFound } from './middleware/error.js';
import { api } from './routes/api.js';
import { channelAllocations } from './routes/channel-allocations.js';
import { integrations } from './routes/integrations.js';
import { onlineOrders } from './routes/online-orders.js';
import { stockRequests } from './routes/stock-requests.js';

export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.FRONTEND_URL.split(',').map((v) => v.trim()), credentials: false }));
app.use(express.json({ limit: '2mb' }));
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 500, standardHeaders: 'draft-8', legacyHeaders: false }));
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use('/api/v1/integrations', requireIntegrationAuth, integrations);
app.use('/api/v1/online-orders', requireAuth, onlineOrders);
app.use('/api/v1/channel-allocations', requireAuth, channelAllocations);
app.use('/api/v1/stock-requests', requireAuth, stockRequests);
app.use('/api/v1', requireAuth, api);
app.use(notFound);
app.use(errorHandler);
